from datetime import datetime, timezone
import xml.etree.ElementTree as ET

import epg_generator as e

def p(start, stop, title="X", channel="c"):
    el = ET.Element("programme", {"start": start, "stop": stop, "channel": channel})
    ET.SubElement(el, "title").text = title
    return el

# Entity matching should work even with a generic EPG title if teams are in description.
events = [{
    "date": "2026-09-12",
    "time": "20:00",
    "title": "FC Porto - FC Alverca Liga Portugal",
    "source": "sportguide",
}]
match, score, details = e.best_external_match(
    "Liga Portugal",
    datetime(2026,9,12,tzinfo=timezone.utc).date(),
    events,
    0.60,
    prog_dt=datetime(2026,9,12,19,0,tzinfo=timezone.utc),
    time_tolerance_minutes=150,
    min_title_score=0.30,
    context_text="Mecz FC Porto - FC Alverca",
    station_timezone="Europe/Lisbon",
    date_tolerance_days=1,
    entity_min_overlap=2,
)
assert match is not None, (score, details)
assert details["entity_overlap"] >= 2

# Autogenerated SportGuide URLs: country-prefixed and /station fallback.
urls = e.generated_sportguide_urls(
    {"name":"PL CANAL+ SPORT","id":"canalplussport.pl"},
    {"sportguide_country":"pl"},
    {"autodiscover_enabled":True,"autodiscover_max_candidates":2,
     "autodiscover_network_keywords":["canal"]},
)
assert urls[0].endswith("/tv-guide-live/pl-canal-sport")
assert urls[1].endswith("/station/canal-sport")

# Mixed timezone cleanup: choose Europe/Paris (+120 in September) rather than UTC duplicates.
programmes = [
    p("20260912090000 +0000","20260912100000 +0000","A"),
    p("20260912100000 +0000","20260912110000 +0000","B"),
    p("20260912110000 +0000","20260912120000 +0000","C"),
    p("20260912090000 +0200","20260912100000 +0200","A"),
    p("20260912100000 +0200","20260912110000 +0200","B"),
    p("20260912110000 +0200","20260912120000 +0200","C"),
]
settings = {
    "mixed_offset_cleanup_enabled": True,
    "mixed_offset_cleanup_min_overlaps": 1,
    "mixed_offset_cleanup_min_group_ratio": 0.2,
    "mixed_offset_cleanup_prefer_source_timezone": True,
    "quality_overlap_warning_minutes": 5,
    "quality_gap_warning_minutes": 180,
    "quality_low_programme_threshold": 1,
}
cleaned, removed, info = e.cleanup_mixed_offset_programmes(programmes, settings, "Europe/Paris")
assert info["applied"] is True
assert info["chosen_offset_minutes"] == 120
assert removed == 3
assert len(cleaned) == 3

print("v3.4 tests OK")
